import mongoose from "mongoose";
import { IPlanDay } from "../../src/models/campaignplan.model";

export interface CampaignContext {
  products: {
    _id: string;
    name: string;
    description?: string;
    price?: number;
  }[];
  instituteName: string;
  instituteDescription?: string;
}

export interface CampaignGraphState {
  campaignId: string;
  userId: string;
  instituteId: string;
  accountId: string;

  // Campaign fields
  name: string;
  goals: string;
  description?: string;
  tone?: string;
  language?: string;
  platforms: string[];
  postsPerDay: number;
  duration: number;
  startsFrom: Date;

  // Fetched at runtime
  context: CampaignContext | null;

  // Generated by planner
  plan: IPlanDay[];

  // Loop tracking
  currentDayIndex: number;
  currentPostIndex: number;
  generatedCount: number;

  // Error handling
  error?: string;
}